repositories {
    mavenLocal()
    exclusiveContent {
        forRepositories(
                mavenCentral(),
                maven { // Anvil Lib
                    name = "Cjsah Maven"
                    url = "https://server.cjsah.net:1002/maven/releases/"
                    content {
                        includeGroup "dev.anvilcraft.lib"
                        includeGroup "dev.anvilcraft.resource"
                        includeGroup "dev.dubhe"
                    }
                }
        )
        filter {
            includeGroup "dev.anvilcraft.lib"
            includeGroup "dev.anvilcraft.resource"
            includeGroup "dev.dubhe"
        }
    }
}
