# Jvm info
java_version=25
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment info
minecraft_version_range=[26.1.1,26.1.2)
neo_version_range=[26.1,)
loader_version_range=[4,)
## Upload info
upload=false
modrinth_id=xxxxx
curseforge_id=xxxxx
## Mod info
mod_id=crash_sinytra
mod_name=CrashWithSinytraConnector
mod_license=MIT
mod_version=1.0.0
maven_group=dev.anvilcraft.crash
mod_authors=Anvil-Dev
mod_description=CrashWithSinytraConnector
